name: Docker Series Builds

on:
  push:
    branches: [ master ]
  #
  # Run this action periodically to keep browsers up-to-date
  # even if there is no activity in this repo.
  #
  schedule:
    - cron: "43 2 * * 1"

env:
  DOCKER_IMAGE: bytear/neko
  DOCKER_TAG: base

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.NEW_DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.NEW_DOCKER_USERNAME }}" --password-stdin
      - name: Login to Docker Hub
        run: |
          docker login -u "bytear" -p "${{ secrets.NEW_DOCKER_PASSWORD }}" docker.io
      
      - name: Re-login docker
        run: docker login -u "bytear" -p "${{ secrets.NEW_DOCKER_PASSWORD }}" docker.io
      - name: Build base
        run: |
          BUILD_IMAGE=${DOCKER_IMAGE} .docker/build ${DOCKER_TAG}
          docker tag ${DOCKER_IMAGE}:${DOCKER_TAG}
          docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
        env:
          DOCKER_TAG: base

  build:
    runs-on: ubuntu-latest
    needs: [ build-base ]
    strategy:
      matrix:
        tags: [ firefox, chromium, google-chrome, ungoogled-chromium, microsoft-edge, brave, tor-browser, vncviewer, vlc, xfce ]
    env:
      DOCKER_TAG: ${{ matrix.tags }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.NEW_DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.NEW_DOCKER_USERNAME }}" --password-stdin
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NEW_DOCKER_USERNAME }}
          password: ${{ secrets.NEW_DOCKER_PASSWORD }}

      - name: Build container
        run: |
          BUILD_IMAGE=${DOCKER_IMAGE} .docker/build ${DOCKER_TAG}
          docker login -u "bytear" -p "${{ secrets.NEW_DOCKER_PASSWORD }}" docker.io
          docker tag ${DOCKER_IMAGE}:${DOCKER_TAG}
          docker push ${DOCKER_IMAGE}:${DOCKER_TAG}
      - name: Push latest tag
        if: ${{ matrix.tags == 'firefox' }}
        run: |
          docker login -u "bytear" -p "${{ secrets.NEW_DOCKER_PASSWORD }}" docker.io
          docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
          docker tag ${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_IMAGE}:latest
          docker push ${DOCKER_IMAGE}:latest
